from main.pieces import Bishop, BlackPawn, King, Knight, Queen, Rook, WhitePawn
from main.x import A, B, C, D, E, F, G, H

WHITE_SCAFFOLD = {
    "king": {"piece_type": King, "x": E, "y": 1, "has_moved": False},
    "queen": {"piece_type": Queen, "x": D, "y": 1},
    "a_rook": {"piece_type": Rook, "x": A, "y": 1, "has_moved": False},
    "h_rook": {"piece_type": Rook, "x": H, "y": 1, "has_moved": False},
    "b_knight": {"piece_type": Knight, "x": B, "y": 1},
    "g_knight": {"piece_type": Knight, "x": G, "y": 1},
    "c_bishop": {"piece_type": Bishop, "x": C, "y": 1},
    "f_bishop": {"piece_type": Bishop, "x": F, "y": 1},
    "a_pawn": {"piece_type": WhitePawn, "x": A, "y": 2},
    "b_pawn": {"piece_type": WhitePawn, "x": B, "y": 2},
    "c_pawn": {"piece_type": WhitePawn, "x": C, "y": 2},
    "d_pawn": {"piece_type": WhitePawn, "x": D, "y": 2},
    "e_pawn": {"piece_type": WhitePawn, "x": E, "y": 2},
    "f_pawn": {"piece_type": WhitePawn, "x": F, "y": 2},
    "g_pawn": {"piece_type": WhitePawn, "x": G, "y": 2},
    "h_pawn": {"piece_type": WhitePawn, "x": H, "y": 2},
}

BLACK_SCAFFOLD = {
    "king": {"piece_type": King, "x": E, "y": 8, "has_moved": False},
    "queen": {"piece_type": Queen, "x": D, "y": 8},
    "a_rook": {"piece_type": Rook, "x": A, "y": 8, "has_moved": False},
    "h_rook": {"piece_type": Rook, "x": H, "y": 8, "has_moved": False},
    "b_knight": {"piece_type": Knight, "x": B, "y": 8},
    "g_knight": {"piece_type": Knight, "x": G, "y": 8},
    "c_bishop": {"piece_type": Bishop, "x": C, "y": 8},
    "f_bishop": {"piece_type": Bishop, "x": F, "y": 8},
    "a_pawn": {"piece_type": BlackPawn, "x": A, "y": 7},
    "b_pawn": {"piece_type": BlackPawn, "x": B, "y": 7},
    "c_pawn": {"piece_type": BlackPawn, "x": C, "y": 7},
    "d_pawn": {"piece_type": BlackPawn, "x": D, "y": 7},
    "e_pawn": {"piece_type": BlackPawn, "x": E, "y": 7},
    "f_pawn": {"piece_type": BlackPawn, "x": F, "y": 7},
    "g_pawn": {"piece_type": BlackPawn, "x": G, "y": 7},
    "h_pawn": {"piece_type": BlackPawn, "x": H, "y": 7},
}

EMPTY_SCAFFOLD = {
    "king": None,
    "queen": None,
    "a_rook": None,
    "h_rook": None,
    "b_knight": None,
    "g_knight": None,
    "c_bishop": None,
    "f_bishop": None,
    "a_pawn": None,
    "b_pawn": None,
    "c_pawn": None,
    "d_pawn": None,
    "e_pawn": None,
    "f_pawn": None,
    "g_pawn": None,
    "h_pawn": None,
    "a_prom": None,
    "b_prom": None,
    "c_prom": None,
    "d_prom": None,
    "e_prom": None,
    "f_prom": None,
    "g_prom": None,
    "h_prom": None,
}
