from main.pieces import Bishop, BlackPawn, King, Knight, Queen, Rook, WhitePawn

WHITE_SCAFFOLD = {
    "king": {"piece_type": King, "x": "e", "y": 1, "has_moved": False},
    "queen": {"piece_type": Queen, "x": "d", "y": 1},
    "a_rook": {"piece_type": Rook, "x": "a", "y": 1, "has_moved": False},
    "h_rook": {"piece_type": Rook, "x": "h", "y": 1, "has_moved": False},
    "b_knight": {"piece_type": Knight, "x": "b", "y": 1},
    "g_knight": {"piece_type": Knight, "x": "g", "y": 1},
    "c_bishop": {"piece_type": Bishop, "x": "c", "y": 1},
    "f_bishop": {"piece_type": Bishop, "x": "f", "y": 1},
    "a_slot": {"piece_type": WhitePawn, "x": "a", "y": 2},
    "b_slot": {"piece_type": WhitePawn, "x": "b", "y": 2},
    "c_slot": {"piece_type": WhitePawn, "x": "c", "y": 2},
    "d_slot": {"piece_type": WhitePawn, "x": "d", "y": 2},
    "e_slot": {"piece_type": WhitePawn, "x": "e", "y": 2},
    "f_slot": {"piece_type": WhitePawn, "x": "f", "y": 2},
    "g_slot": {"piece_type": WhitePawn, "x": "g", "y": 2},
    "h_slot": {"piece_type": WhitePawn, "x": "h", "y": 2},
}

BLACK_SCAFFOLD = {
    "king": {"piece_type": King, "x": "e", "y": 8, "has_moved": False},
    "queen": {"piece_type": Queen, "x": "d", "y": 8},
    "a_rook": {"piece_type": Rook, "x": "a", "y": 8, "has_moved": False},
    "h_rook": {"piece_type": Rook, "x": "h", "y": 8, "has_moved": False},
    "b_knight": {"piece_type": Knight, "x": "b", "y": 8},
    "g_knight": {"piece_type": Knight, "x": "g", "y": 8},
    "c_bishop": {"piece_type": Bishop, "x": "c", "y": 8},
    "f_bishop": {"piece_type": Bishop, "x": "f", "y": 8},
    "a_slot": {"piece_type": BlackPawn, "x": "a", "y": 7},
    "b_slot": {"piece_type": BlackPawn, "x": "b", "y": 7},
    "c_slot": {"piece_type": BlackPawn, "x": "c", "y": 7},
    "d_slot": {"piece_type": BlackPawn, "x": "d", "y": 7},
    "e_slot": {"piece_type": BlackPawn, "x": "e", "y": 7},
    "f_slot": {"piece_type": BlackPawn, "x": "f", "y": 7},
    "g_slot": {"piece_type": BlackPawn, "x": "g", "y": 7},
    "h_slot": {"piece_type": BlackPawn, "x": "h", "y": 7},
}

EMPTY_SCAFFOLD = {
    "king": None,
    "queen": None,
    "a_rook": None,
    "h_rook": None,
    "b_knight": None,
    "g_knight": None,
    "c_bishop": None,
    "f_bishop": None,
    "a_slot": None,
    "b_slot": None,
    "c_slot": None,
    "d_slot": None,
    "e_slot": None,
    "f_slot": None,
    "g_slot": None,
    "h_slot": None,
}
